server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

jwt:
  signer-key: ${SIGNER_KEY}
  valid-duration: ${VALID_DURATION}
  refresh-duration: ${REFRESH_DURATION}

account:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}